labels:
  0: person
  1: bicycle
  2: car
  3: motorcycle
  4: bus
  5: truck
  6: traffic light
  7: stop sign
  8: parking meter
  9: bench
  10: sheep
  11: crosswalk

conf: 0.3   # lower bound to publish prediction